table:
  name: escrow_pending_approvals
  schema: public
configuration:
  column_config:
    escrow_id:
      custom_name: escrowId
    field_changed:
      custom_name: fieldChanged
    old_value:
      custom_name: oldValue
    new_value:
      custom_name: newValue
    changed_by_role:
      custom_name: changedByRole
    changed_by_user_id:
      custom_name: changedByUserId
    requires_customer_approval:
      custom_name: requiresCustomerApproval
    customer_approved:
      custom_name: customerApproved
    customer_approved_at:
      custom_name: customerApprovedAt
    customer_wallet_address:
      custom_name: customerWalletAddress
    unsigned_xdr:
      custom_name: unsignedXdr
    signed_xdr:
      custom_name: signedXdr
    expires_at:
      custom_name: expiresAt
    created_at:
      custom_name: createdAt
    tenant_id:
      custom_name: tenantId
  custom_name: escrowPendingApprovals

# ─── Relationships ────────────────────────────────────────────────────────────
object_relationships:
  - name: escrow
    using:
      foreign_key_constraint_on: escrow_id

# ─── Permissions ──────────────────────────────────────────────────────────────

# user: customer can only see their own pending approvals (matched by wallet address)
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - escrow_id
        - field_changed
        - old_value
        - new_value
        - changed_by_role
        - requires_customer_approval
        - customer_approved
        - customer_approved_at
        - customer_wallet_address
        - unsigned_xdr
        - status
        - expires_at
        - created_at
        - tenant_id
      filter:
        _and:
          - tenant_id:
              _eq: X-Hasura-Tenant-Id
          - customer_wallet_address:
              _eq: X-Hasura-Wallet-Address
  - role: admin
    permission:
      columns: "*"
      filter:
        tenant_id:
          _eq: X-Hasura-Tenant-Id
  - role: superadmin
    permission:
      columns: "*"
      filter: {}

# user: customer submits their signed XDR and flips status to approved/rejected
update_permissions:
  - role: user
    permission:
      columns:
        - signed_xdr
        - customer_approved
        - customer_approved_at
        - status
      filter:
        _and:
          - tenant_id:
              _eq: X-Hasura-Tenant-Id
          - customer_wallet_address:
              _eq: X-Hasura-Wallet-Address
          - status:
              _eq: pending_approval
      check:
        status:
          _in:
            - approved
            - rejected
  - role: admin
    permission:
      columns:
        - status
        - unsigned_xdr
        - signed_xdr
        - customer_approved
        - customer_approved_at
        - expires_at
      filter:
        tenant_id:
          _eq: X-Hasura-Tenant-Id
      check: {}
  - role: superadmin
    permission:
      columns: "*"
      filter: {}
      check: {}

# ─── Event Trigger ────────────────────────────────────────────────────────────
event_triggers:
  - name: on_escrow_approval_required
    definition:
      enable_manual: false
      insert:
        columns: "*"
    retry_conf:
      num_retries: 3
      interval_sec: 10
      timeout_sec: 60
    webhook: "{{WEBHOOK_BASE_URL}}/webhooks/escrow/approval-required"
    headers:
      - name: x-webhook-secret
        value_from_env: WEBHOOK_SECRET
    clean_up_config:
      clean_up_interval_in_mins: 10080   # 7 days
      batch_size: 100
      timeout_in_secs: 60
      paused: false
